Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2018-12, with the labels that each got.

#53 use go 1.10
  Gopkg.lock
  automation/check-patch.packages
  automation/check-patch.sh
  docs/devel-guide.md
  pkg/plugin/ns.go
  pkg/plugin/plugin.go
Labels: size/L

#60 Update our providers.
  automation/check-patch.k8s-multus-1.12.2-release.mounts
  automation/check-patch.k8s-multus-1.12.2-release.packages
  automation/check-patch.k8s-multus-1.12.2-release.sh
  automation/check-patch.openshift-3.11-multus-release.mounts
  automation/check-patch.openshift-3.11-multus-release.packages
  automation/check-patch.openshift-3.11-multus-release.sh
  automation/test.sh
  cluster/ephemeral-provider-common.sh
  cluster/k8s-multus-1.12.2/README.md
  cluster/k8s-multus-1.12.2/provider.sh
  cluster/os-3.11.0-multus/README.md
  cluster/os-3.11.0-multus/provider.sh
  cluster/os-3.11.0/README.md
  cluster/os-3.11.0/provider.sh
  hack/common.sh
  stdci.yaml
Labels: size/M

#59 Add selector to ovs-vsctl template
  examples/openshift-ovs-vsctl.yml
Labels: size/XS

#61 Support specifying mac address in the pod network annotation
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: size/M
