Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2018-10, with the labels that each got.

#43 Fix yaml files.
  examples/openshift-ovs-vsctl.yml
  examples/ovs-cni.yml
  manifests/openshift-ovs-vsctl.yml.in
  manifests/ovs-cni.yml.in
Labels: size/XS

#39 Setup providers
  automation/check-patch.sh
  automation/test.sh
  cluster/k8s-multus-1.11.1/provider.sh
  cluster/os-3.10.0-multus/provider.sh
  cluster/up.sh
Labels: size/L

#40 Added travis merge
  .travis.yml
Labels: size/S

#46 Add cluster-sync to test.sh.
  automation/test.sh
Labels: size/XS

#45 Add travis merge fuction
  .travis.yml
Labels: size/XS

#47 Remove kubevirt from stdci deployment.
  automation/test.sh
Labels: size/XS
