Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2019-03, with the labels that each got.

#69 Use `/usr/bin/env bash` instead of `/bin/bash` for build scripts
  hack/build-func-tests.sh
  hack/build-manifests.sh
  hack/common.sh
  hack/docker-builder/entrypoint.sh
  hack/functests.sh
  hack/get_tag.sh
  hack/get_version.sh
  hack/test-dockerized.sh
  hack/version.sh
Labels: size/S

#68 Fixed `make build`
  automation/check-patch.sh
  cmd/marker/main.go
  cmd/plugin/main.go
  hack/docker-builder/rsyncd.conf
  hack/dockerized
  hack/test-dockerized.sh
  tests/marker_test.go
Labels: size/S

#71 fix import path in .travis.yml script
  .travis.yml
Labels: size/XS

#70 Don't copy ovs-vsctl to system directories
  examples/openshift-ovs-cni.yml
  manifests/openshift-ovs-cni.yml.in
Labels: size/M
