Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2019-11, with the labels that each got.

#85 bump used base images to Fedora 31
  cmd/marker/Dockerfile
  cmd/plugin/Dockerfile
  hack/docker-builder/Dockerfile
Labels: dco-signoff: yes, size/S

#86 deploy on arbitrary cluster via CNAO
  docs/deployment-on-arbitrary-cluster.md
Labels: dco-signoff: yes, size/M

#90 Move to ubi8-minimal
  cmd/marker/Dockerfile
  cmd/plugin/Dockerfile
  pkg/plugin/plugin.go
Labels: dco-signoff: yes, size/S

#89 use Go 1.12 on travis
  .travis.yml
  Makefile
Labels: dco-signoff: yes, size/XS

#91 drop multus and openshift
  automation/check-merged.environment.yaml
  automation/check-merged.mounts
  automation/check-merged.packages
  automation/check-merged.sh
  automation/check-patch.k8s-multus-1.12.2-release.mounts
  automation/check-patch.k8s-multus-1.12.2-release.packages
  automation/check-patch.k8s-multus-1.12.2-release.sh
  automation/check-patch.openshift-3.11-multus-release.mounts
  automation/check-patch.openshift-3.11-multus-release.packages
  automation/check-patch.openshift-3.11-multus-release.sh
  automation/test.sh
  docs/devel-guide.md
  examples/flannel-multus.yml
  examples/openshift-multus.yml
  hack/build-manifests.sh
  hack/common.sh
  manifests/flannel-multus.yml.in
  manifests/openshift-multus.yml.in
  stdci.yaml
Labels: dco-signoff: yes, size/XL

#92 Make bridge mac optional
  pkg/plugin/plugin.go
Labels: dco-signoff: yes, size/M

#93 Remove bridge from report
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: dco-signoff: yes, size/M
