Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2020-11, with the labels that each got.

#135 tier1, Change KUBECONFIG to be configurable in functest
  hack/functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#136 ci, Add .travis.yml ci file
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#138 go-install, Add vendored go
  .gitignore
  Makefile
  hack/install-go.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#137 send gratuitous arp upon assigning ip address
  go.mod
  pkg/ovsdb/ovsdb.go
  pkg/plugin/plugin.go
  vendor/github.com/j-keck/arping/.gitignore
  vendor/github.com/j-keck/arping/LICENSE
  vendor/github.com/j-keck/arping/README.md
  vendor/github.com/j-keck/arping/arp_datagram.go
  vendor/github.com/j-keck/arping/arping.go
  vendor/github.com/j-keck/arping/arping_bsd.go
  vendor/github.com/j-keck/arping/arping_linux.go
  vendor/github.com/j-keck/arping/arping_windows.go
  vendor/github.com/j-keck/arping/netutils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#139 ci, Use vendored-go in functest
  Makefile
  hack/functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#134 Fix interface index in result.IPs
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#141 update deprecated api version
  examples/ovs-cni.yml
  manifests/ovs-cni.yml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#142 make ovs socket file path as configurable property
  docs/cni-plugin.md
  pkg/ovsdb/ovsdb.go
  pkg/plugin/plugin.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
