Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2020-02, with the labels that each got.

#102 add ipam support
  docs/cni-plugin.md
  hack/docker-builder/Dockerfile
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args_test.go
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate_test.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec_test.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/cni_args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/version_decoder.go
  vendor/github.com/containernetworking/cni/pkg/invoke/find.go
  vendor/github.com/containernetworking/cni/pkg/invoke/find_test.go
  vendor/github.com/containernetworking/cni/pkg/invoke/get_version_integration_test.go
  vendor/github.com/containernetworking/cni/pkg/invoke/invoke_suite_test.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_windows.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec_test.go
  vendor/github.com/containernetworking/plugins/pkg/ipam/ipam.go
  vendor/github.com/containernetworking/plugins/pkg/ipam/ipam_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ipam/ipam_linux_test.go
  vendor/github.com/containernetworking/plugins/pkg/ipam/ipam_suite_test.go
  vendor/github.com/containernetworking/plugins/pkg/utils/sysctl/sysctl_linux.go
  vendor/github.com/containernetworking/plugins/pkg/utils/sysctl/sysctl_linux_test.go
  vendor/github.com/containernetworking/plugins/pkg/utils/sysctl/sysctl_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#103 Add Mellanox SRIOV hw-offload support
  docs/ovs-offload.md
  go.mod
  go.sum
  pkg/plugin/plugin.go
  pkg/sriov/cache.go
  pkg/sriov/sriov.go
  vendor/github.com/Mellanox/sriovnet/.travis.yml
  vendor/github.com/Mellanox/sriovnet/LICENSE
  vendor/github.com/Mellanox/sriovnet/README.md
  vendor/github.com/Mellanox/sriovnet/file_access.go
  vendor/github.com/Mellanox/sriovnet/mofed_ib_helper.go
  vendor/github.com/Mellanox/sriovnet/pkg/utils/filesystem/defaultfs.go
  vendor/github.com/Mellanox/sriovnet/pkg/utils/filesystem/fakefs.go
  vendor/github.com/Mellanox/sriovnet/pkg/utils/filesystem/filesystem.go
  vendor/github.com/Mellanox/sriovnet/sriovnet.go
  vendor/github.com/Mellanox/sriovnet/sriovnet_helper.go
  vendor/github.com/Mellanox/sriovnet/sriovnet_switchdev.go
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/codec.go
  vendor/github.com/satori/go.uuid/generator.go
  vendor/github.com/satori/go.uuid/sql.go
  vendor/github.com/satori/go.uuid/uuid.go
  vendor/github.com/spf13/afero/.travis.yml
  vendor/github.com/spf13/afero/LICENSE.txt
  vendor/github.com/spf13/afero/README.md
  vendor/github.com/spf13/afero/afero.go
  vendor/github.com/spf13/afero/appveyor.yml
  vendor/github.com/spf13/afero/basepath.go
  vendor/github.com/spf13/afero/cacheOnReadFs.go
  vendor/github.com/spf13/afero/const_bsds.go
  vendor/github.com/spf13/afero/const_win_unix.go
  vendor/github.com/spf13/afero/copyOnWriteFs.go
  vendor/github.com/spf13/afero/go.mod
  vendor/github.com/spf13/afero/go.sum
  vendor/github.com/spf13/afero/httpFs.go
  vendor/github.com/spf13/afero/ioutil.go
  vendor/github.com/spf13/afero/lstater.go
  vendor/github.com/spf13/afero/match.go
  vendor/github.com/spf13/afero/mem/dir.go
  vendor/github.com/spf13/afero/mem/dirmap.go
  vendor/github.com/spf13/afero/mem/file.go
  vendor/github.com/spf13/afero/mem/file_test.go
  vendor/github.com/spf13/afero/memmap.go
  vendor/github.com/spf13/afero/os.go
  vendor/github.com/spf13/afero/path.go
  vendor/github.com/spf13/afero/readonlyfs.go
  vendor/github.com/spf13/afero/regexpfs.go
  vendor/github.com/spf13/afero/sftpfs/file.go
  vendor/github.com/spf13/afero/sftpfs/sftp.go
  vendor/github.com/spf13/afero/sftpfs/sftp_test_go
  vendor/github.com/spf13/afero/unionFile.go
  vendor/github.com/spf13/afero/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#104 cni-plugin.md: document "mtu" and "trunk"
  docs/cni-plugin.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#108 update README.md
  README.md
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS
