Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2020-09, with the labels that each got.

#127 Fix Link Error in deployment-on-arbitrary-cluster.md
  docs/deployment-on-arbitrary-cluster.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#128 Bump openvswitch to version 2.13
  cluster/up.sh
  hack/docker-builder/Dockerfile
  pkg/plugin/plugin_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#129 handle smartnic cleanup when container net namespace is empty
  pkg/plugin/plugin.go
  pkg/sriov/sriov.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
