Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2020-01, with the labels that each got.

#95 Upgrade DaemonSet to apps/v1
  examples/ovs-cni.yml
  manifests/ovs-cni.yml.in
Labels: dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#97 Add support for trunk with selective vlans
  pkg/ovsdb/ovsdb.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, ok-to-test, size/L

#98 add OWNERS file
  OWNERS
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed
