Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2021-08, with the labels that each got.

#189 tests, marker: increase timeout
  tests/marker_test.go
Labels: release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#187 Set max unavailable to 10%
  manifests/ovs-cni.yml.in
Labels: release-note-none, dco-signoff: yes, lgtm, approved

#192 Update rendered manifest example
  examples/ovs-cni.yml
Labels: release-note-none, dco-signoff: yes, lgtm, approved

#190 Bump libovsdb to 0.6.0
  go.mod
  go.sum
  vendor/github.com/cenkalti/backoff/v4/.gitignore
  vendor/github.com/cenkalti/backoff/v4/.travis.yml
  vendor/github.com/cenkalti/backoff/v4/LICENSE
  vendor/github.com/cenkalti/backoff/v4/README.md
  vendor/github.com/cenkalti/backoff/v4/backoff.go
  vendor/github.com/cenkalti/backoff/v4/context.go
  vendor/github.com/cenkalti/backoff/v4/exponential.go
  vendor/github.com/cenkalti/backoff/v4/go.mod
  vendor/github.com/cenkalti/backoff/v4/retry.go
  vendor/github.com/cenkalti/backoff/v4/ticker.go
  vendor/github.com/cenkalti/backoff/v4/timer.go
  vendor/github.com/cenkalti/backoff/v4/tries.go
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/go.mod
  vendor/github.com/imdario/mergo/go.sum
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/ovn-org/libovsdb/cache/cache.go
  vendor/github.com/ovn-org/libovsdb/client/api.go
  vendor/github.com/ovn-org/libovsdb/client/client.go
  vendor/github.com/ovn-org/libovsdb/client/options.go
  vendor/github.com/ovn-org/libovsdb/ovsdb/condition.go
  vendor/github.com/ovn-org/libovsdb/ovsdb/map.go
  vendor/github.com/ovn-org/libovsdb/ovsdb/mutation.go
  vendor/github.com/ovn-org/libovsdb/ovsdb/notation.go
  vendor/github.com/ovn-org/libovsdb/ovsdb/schema.go
  vendor/github.com/ovn-org/libovsdb/ovsdb/set.go
  vendor/modules.txt
Labels: release-note, dco-signoff: yes, ok-to-test, lgtm, approved

#197 Fix Broken Link to Cluster Network Addon Operator
  docs/deployment-on-arbitrary-cluster.md
Labels: release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved
