Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2021-06, with the labels that each got.

#160 use cached netconf to avoid delete loop
  pkg/config/config.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/sriov/sriov.go
  pkg/types/types.go
  pkg/utils/cache.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#164 DaemonSet, Add Priority class
  examples/ovs-cni.yml
  manifests/ovs-cni.yml.in
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#166 docker, add virtual-tag docker-tag
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#165 travis, Remove travis script
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#167 multus, Update multus manifest
  cluster/multus-daemonset.do-not-change.yml
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#170 clean up assigned ip address in ipam test
  pkg/plugin/plugin_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#172 [release-0.19] DaemonSet, Add Priority class
  examples/ovs-cni.yml
  manifests/ovs-cni.yml.in
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#168 Fix a failure of plugin test
  Makefile
  docs/cni-plugin.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#173 Modify data directory of host-local IPAM plugin
  pkg/plugin/plugin_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none
