Repository k8snetworkplumbingwg/ovs-cni, pull requests merged in 2021-09, with the labels that each got.

#200 Download Go directly without gimme
  hack/docker-builder/Dockerfile
  hack/docker-builder/entrypoint.sh
Labels: release-note-none, dco-signoff: yes, lgtm, approved

#191 Bump openvswitch to 2.15
  cluster/up.sh
  hack/docker-builder/Dockerfile
Labels: release-note, dco-signoff: yes, ok-to-test, lgtm, approved

#198 Remove Go installation from automation/setup.sh
  automation/setup.sh
Labels: release-note-none, dco-signoff: yes, lgtm, approved

#201 Bump Kubernetes to 1.20
  automation/check-patch.e2e.sh
  cluster/kubevirtci.sh
Labels: release-note, dco-signoff: yes, ok-to-test, lgtm, approved

#202 Bump Go to 1.16.8
  hack/docker-builder/Dockerfile
  hack/install-go.sh
Labels: release-note, dco-signoff: yes, ok-to-test, lgtm, approved

#203 Bump CNI plugin to 0.9.1
  hack/docker-builder/Dockerfile
Labels: release-note, dco-signoff: yes, ok-to-test, lgtm, approved

#205 derive container mac address from ip address
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: release-note-none, dco-signoff: yes, lgtm, approved

#204 Fix make cluster-sync failure with latest kubevirtci
  cluster/kubevirtci.sh
  cluster/sync.sh
Labels: release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#209 Bump CNI plugin to 1.0.1
  Makefile
  hack/docker-builder/Dockerfile
Labels: release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#208 Bump Kubernetes to 1.22
  cluster/kubevirtci.sh
  examples/ovs-cni.yml
  manifests/ovs-cni.yml.in
Labels: release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#211 extend mac randomness to 4 bytes for no ip case
  pkg/plugin/plugin.go
Labels: release-note-none, dco-signoff: yes, lgtm, approved
